# Generated by Django 3.0.5 on 2020-04-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_questao', models.CharField(max_length=200)),
                ('data_publicacao', models.DateTimeField(verbose_name='Data Publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Escolhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_escolha', models.CharField(max_length=100)),
                ('votos', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.Questao')),
            ],
        ),
    ]
